name: Release

on:
  push:
    tags:
      - 'v*'

permissions: 
  id-token: write 
  contents: write 
  attestations: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Extract version from plugin.json
        id: extract_version
        run: |
          VERSION=$(grep -o '"version": *"[^"]*"' src/plugin.json | grep -o '"[^"]*"$' | tr -d '"')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: Install dependencies
        run: npm ci
        
      - uses: grafana/plugin-actions/build-plugin@main
        with:
          policy_token: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
          attestation: true
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            skylineintelligence-forecasting-app-*.zip
            skylineintelligence-forecasting-app-*.zip.sha1
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        