name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build plugin
        run: npm run build
        
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
      
      - name: Install Mage
        run: |
          go install github.com/magefile/mage@latest
          
      - name: Build backend
        run: |
          go mod download
          mage -v
          
      - name: Sign plugin
        run: npm run sign
        env:
          GRAFANA_ACCESS_POLICY_TOKEN: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
          
      - name: Get plugin metadata
        id: metadata
        run: |
          echo "PLUGIN_NAME=$(cat dist/plugin.json | jq -r .id)" >> $GITHUB_OUTPUT
          echo "PLUGIN_VERSION=$(cat dist/plugin.json | jq -r .info.version)" >> $GITHUB_OUTPUT
          
      - name: Package plugin
        run: |
          mkdir -p ${{ steps.metadata.outputs.PLUGIN_NAME }}
          cp -r dist/* ${{ steps.metadata.outputs.PLUGIN_NAME }}
          zip -r ${{ steps.metadata.outputs.PLUGIN_NAME }}-${{ steps.metadata.outputs.PLUGIN_VERSION }}.zip ${{ steps.metadata.outputs.PLUGIN_NAME }}
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.metadata.outputs.PLUGIN_NAME }}-${{ steps.metadata.outputs.PLUGIN_VERSION }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}